name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write    
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: mariadb-11.1.2-winx64\bin
          
      - name: installer
        shell: cmd
        run: |
          curl https://dlm.mariadb.com/3407681/MariaDB/mariadb-11.1.2/winx64-packages/mariadb-11.1.2-winx64.zip -L -O
          
      - shell: cmd
        run: |
          7z.exe a mariadb-11.1.2-winx64.zip mariadb-11.1.2-winx64\bin\create-table.cmd
          7z.exe a mariadb-11.1.2-winx64.zip mariadb-11.1.2-winx64\bin\mariadbd.exe.Portable.cmd
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: mariadb-11.1.2-winx64.zip
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
